<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Amits-MacBook-Pro.local" ignored="1" name="Default test(failed)" tests="2" failures="2" timestamp="2022-07-11T16:36:01 IST" time="0.091" errors="0">
  <testcase name="test12" time="0.014" classname="Tests.Testngretryfaileddemo">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at Tests.Testngretryfaileddemo.test12(Testngretryfaileddemo.java:15)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test12 -->
  <testcase name="test3" time="0.006" classname="Tests.Testngretryfaileddemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Tests.Testngretryfaileddemo.test3(Testngretryfaileddemo.java:21)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="Tests.Testngretryfaileddemo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
